Repository knative-sandbox/discovery, pull requests merged in 2020-11, with the labels that each got.

#114 [release-0.18] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/discovery/v1alpha1/clusterducktype/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#115 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#116 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/performance-tests.sh
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#118 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/L

#119 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/S

#121 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/reconciler/testing/tracker.go
  vendor/knative.dev/pkg/tracker/enqueue.go
  vendor/knative.dev/pkg/tracker/interface.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#120 Use the new knative-sandbox/reconciler-test framework
  go.mod
  go.sum
  pkg/reconciler/clusterducktype/clusterducktype_test.go
  test/e2e/config/smoke/smoke.go
  test/e2e/main_test.go
  test/e2e/publish_test.go
  test/e2e/smoke_test.go
  third_party/VENDOR-LICENSE/knative.dev/reconciler-test/pkg/LICENSE
  vendor/github.com/n3wscott/rigging/.gitignore
  vendor/github.com/n3wscott/rigging/AUTHORS
  vendor/github.com/n3wscott/rigging/README.md
  vendor/github.com/n3wscott/rigging/go.mod
  vendor/github.com/n3wscott/rigging/go.sum
  vendor/github.com/n3wscott/rigging/pkg/lifecycle/lifecycle.go
  vendor/github.com/n3wscott/rigging/rigging.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/knative.dev/pkg/test/logstream/v2/stream.go
  vendor/knative.dev/reconciler-test/LICENSE
  vendor/knative.dev/reconciler-test/pkg/environment/flags.go
  vendor/knative.dev/reconciler-test/pkg/environment/images.go
  vendor/knative.dev/reconciler-test/pkg/environment/interfaces.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/environment/namespace.go
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
  vendor/knative.dev/reconciler-test/pkg/feature/level.go
  vendor/knative.dev/reconciler-test/pkg/feature/name.go
  vendor/knative.dev/reconciler-test/pkg/feature/states.go
  vendor/knative.dev/reconciler-test/pkg/feature/timing.go
  vendor/knative.dev/reconciler-test/pkg/images/cmd.go
  vendor/knative.dev/reconciler-test/pkg/images/ko.go
  vendor/knative.dev/reconciler-test/pkg/k8s/job.go
  vendor/knative.dev/reconciler-test/pkg/k8s/logs.go
  vendor/knative.dev/reconciler-test/pkg/k8s/pod.go
  vendor/knative.dev/reconciler-test/pkg/k8s/wait.go
  vendor/knative.dev/reconciler-test/pkg/manifest/installer.go
  vendor/knative.dev/reconciler-test/pkg/manifest/manifest.go
  vendor/knative.dev/reconciler-test/pkg/manifest/templates.go
  vendor/knative.dev/reconciler-test/pkg/manifest/yaml.go
  vendor/modules.txt
Labels: approved, cla: yes, kind/cleanup, lgtm, size/XXL

#123 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/openzipkin/zipkin-go/LICENSE
  vendor/github.com/openzipkin/zipkin-go/model/annotation.go
  vendor/github.com/openzipkin/zipkin-go/model/doc.go
  vendor/github.com/openzipkin/zipkin-go/model/endpoint.go
  vendor/github.com/openzipkin/zipkin-go/model/kind.go
  vendor/github.com/openzipkin/zipkin-go/model/span.go
  vendor/github.com/openzipkin/zipkin-go/model/span_id.go
  vendor/github.com/openzipkin/zipkin-go/model/traceid.go
  vendor/go.opencensus.io/plugin/ochttp/propagation/tracecontext/propagation.go
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/hack/update-k8s-deps.sh
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/knative.dev/pkg/network/network.go
  vendor/knative.dev/pkg/test/README.md
  vendor/knative.dev/pkg/test/cleanup.go
  vendor/knative.dev/pkg/test/clients.go
  vendor/knative.dev/pkg/test/crd.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/flags/e2e_flags.go
  vendor/knative.dev/pkg/test/ingress/ingress.go
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/knative.dev/pkg/test/logging/logging.go
  vendor/knative.dev/pkg/test/monitoring/doc.go
  vendor/knative.dev/pkg/test/monitoring/monitoring.go
  vendor/knative.dev/pkg/test/presubmit-tests.sh
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/spoof/error_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/test/test-reconciler-codegen.sh
  vendor/knative.dev/pkg/test/tinterface.go
  vendor/knative.dev/pkg/test/zipkin/doc.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/pkg/tracing/config/doc.go
  vendor/knative.dev/pkg/tracing/config/tracing.go
  vendor/knative.dev/pkg/tracing/config/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/tracing/propagation/http_format_sequence.go
  vendor/knative.dev/pkg/tracing/propagation/tracecontextb3/http_format.go
  vendor/knative.dev/pkg/webhook/env.go
  vendor/knative.dev/reconciler-test/pkg/environment/flags.go
  vendor/knative.dev/reconciler-test/pkg/environment/interfaces.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
  vendor/knative.dev/reconciler-test/pkg/k8s/events.go
  vendor/knative.dev/reconciler-test/pkg/k8s/steps.go
  vendor/knative.dev/reconciler-test/pkg/k8s/wait.go
  vendor/knative.dev/reconciler-test/pkg/manifest/templates.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL
