Repository knative-sandbox/discovery, pull requests merged in 2020-07, with the labels that each got.

#17 Add lberk to approvers
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#18 adding api shape to talk talking about DuckType
  config/300-ducktype.yaml
  config/controller.yaml
  config/webhook.yaml
  go.mod
  pkg/apis/discovery/v1alpha1/ducktype_lifecycle.go
  pkg/apis/discovery/v1alpha1/ducktype_types.go
  pkg/apis/discovery/v1alpha1/ducktype_validation.go
  pkg/apis/discovery/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/ducktype/controller.go
  pkg/reconciler/ducktype/ducktype.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/service/service.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#19 Add crdlister/informer to controller & reconciler
  pkg/reconciler/ducktype/controller.go
  pkg/reconciler/ducktype/ducktype.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#20 adding tests and defaulting, and validation to the api
  go.mod
  go.sum
  pkg/apis/discovery/v1alpha1/ducktype_defaults.go
  pkg/apis/discovery/v1alpha1/ducktype_defaults_test.go
  pkg/apis/discovery/v1alpha1/ducktype_lifecycle.go
  pkg/apis/discovery/v1alpha1/ducktype_lifecycle_test.go
  pkg/apis/discovery/v1alpha1/ducktype_types.go
  pkg/apis/discovery/v1alpha1/ducktype_types_test.go
  pkg/apis/discovery/v1alpha1/ducktype_validation.go
  pkg/apis/discovery/v1alpha1/ducktype_validation_test.go
  pkg/apis/discovery/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#21 enable testing
  .github/workflows/go-build.yaml
  .github/workflows/go-style.yaml
  .github/workflows/go-test.yaml
  pkg/apis/discovery/v1alpha1/ducktype_types.go
  pkg/apis/discovery/v1alpha1/zz_generated.deepcopy.go
  test/presubmit-tests.sh
  third_party/VENDOR-LICENSE/k8s.io/apiextensions-apiserver/pkg/LICENSE
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/defaults.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.pb.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.proto
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/marshal.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types_jsonschema.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.defaults.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/clientset.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/apiextensions_client.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/generated_expansion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/apiextensions_client.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/generated_expansion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/interface.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1/interface.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1beta1/interface.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/factory.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/generic.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1/expansion_generated.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1beta1/expansion_generated.go
  vendor/knative.dev/pkg/client/injection/apiextensions/client/client.go
  vendor/knative.dev/pkg/client/injection/apiextensions/informers/apiextensions/v1/customresourcedefinition/customresourcedefinition.go
  vendor/knative.dev/pkg/client/injection/apiextensions/informers/factory/factory.go
Labels: approved, cla: yes, lgtm, size/XXL

#22 adding code verify step
  .github/workflows/go-build.yaml
  .github/workflows/go-style.yaml
  .github/workflows/go-test.yaml
  .github/workflows/go-verify.yaml
Labels: approved, cla: yes, lgtm, size/M

#23 Add Addressable example yaml
  config/knative/addressable.yaml
Labels: approved, cla: yes, lgtm, size/M

#27 Remove reconcile normal event
  pkg/reconciler/ducktype/ducktype.go
Labels: approved, cla: yes, lgtm, size/S

#28 capitalize addressable name in example yaml
  config/knative/addressable.yaml
Labels: approved, cla: yes, lgtm, size/XS

#26 move to clusterscoped genclient
  pkg/apis/discovery/v1alpha1/ducktype_types.go
  pkg/client/clientset/versioned/typed/discovery/v1alpha1/discovery_client.go
  pkg/client/clientset/versioned/typed/discovery/v1alpha1/ducktype.go
  pkg/client/clientset/versioned/typed/discovery/v1alpha1/fake/fake_discovery_client.go
  pkg/client/clientset/versioned/typed/discovery/v1alpha1/fake/fake_ducktype.go
  pkg/client/informers/externalversions/discovery/v1alpha1/ducktype.go
  pkg/client/informers/externalversions/discovery/v1alpha1/interface.go
  pkg/client/injection/reconciler/discovery/v1alpha1/ducktype/reconciler.go
  pkg/client/listers/discovery/v1alpha1/ducktype.go
  pkg/client/listers/discovery/v1alpha1/expansion_generated.go
Labels: approved, cla: yes, lgtm, size/XS

#30 Adding github action to auto-update the repo via a PR, 2x daily.
  .github/workflows/upgrade.yaml
Labels: approved, cla: yes, lgtm, size/M
