Repository knative-sandbox/discovery, pull requests merged in 2020-12, with the labels that each got.

#124 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/client/client.go
  vendor/knative.dev/hack/microbenchmarks.sh
  vendor/knative.dev/pkg/client/injection/apiextensions/client/client.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/spoof/request.go
  vendor/knative.dev/pkg/test/spoof/response_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/feature/collapse.go
  vendor/knative.dev/reconciler-test/pkg/k8s/steps.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#122 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#126 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/microbenchmarks.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#125 Use new out of gopath codegen
  go.sum
  hack/update-codegen.sh
Labels: approved, cla: yes, lgtm, size/S
