Repository knative-sandbox/discovery, pull requests merged in 2020-09, with the labels that each got.

#53 Design doc to md
  README.md
  docs/proposal.md
Labels: approved, cla: yes, lgtm, size/L

#54 Use kind.local
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/S

#55 Add linting config and fix issues.
  .golangci.yaml
  pkg/apis/discovery/v1alpha1/clusterducktype_validation.go
  pkg/collection/ducks.go
  pkg/collection/resources.go
  pkg/reconciler/clusterducktype/clusterducktype.go
  pkg/reconciler/clusterducktype/clusterducktype_test.go
Labels: approved, cla: yes, lgtm, size/M

#56 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/L

#58 [master] Format markdown
  test/kind/README.md
Labels: approved, cla: yes, lgtm, size/XS

#62 make discovery repo releasable
  .github/workflows/go-pr-build.yaml
  .github/workflows/go-pr-style.yaml
  .github/workflows/go-pr-test.yaml
  .github/workflows/go-pr-verify.yaml
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/L

#60 trying out codecov, might need more app auth on the github side
  .codecov.yaml
  .github/workflows/knative-go-test.yaml
Labels: approved, cla: yes, lgtm, size/S

#63 Demo codecov, adding unit test
  pkg/apis/discovery/v1alpha1/clusterducktype_lifecycle_test.go
  pkg/apis/discovery/v1alpha1/clusterducktype_types_test.go
Labels: approved, cla: yes, lgtm, size/S

#64 [master] Update GitHub Actions
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/L

#70 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
Labels: approved, cla: yes, lgtm, size/M

#76 [Automated] Fix misspellings
  test/e2e-common.sh
Labels: approved, cla: yes, lgtm, size/XS

#75 [Automated] Update actions
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/XS

#77 [Automated] Update actions
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/M
