Repository knative-sandbox/discovery, pull requests merged in 2020-08, with the labels that each got.

#31 adding readme based on PoC and design doc
  README.md
Labels: approved, cla: yes, lgtm, size/L

#32 Update addressible example to match readme
  config/knative/addressable.yaml
Labels: approved, cla: yes, lgtm, size/M

#35 adding anti-affinity to control plane objects
  config/controller.yaml
  config/webhook.yaml
Labels: approved, cla: yes, lgtm, size/S

#36 Reconciler first pass
  config/300-clusterducktype.yaml
  config/400-webhook-service.yaml
  config/500-webhook-configuration.yaml
  config/knative/addressables.duck.knative.dev.yaml
  config/knative/podspecables.duck.knative.dev.yaml
  config/webhook.yaml
  hack/az-control-plane.patch
  hack/update-deps.sh
  pkg/reconciler/clusterducktype/clusterducktype.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/reconcile_config.go
Labels: approved, cla: yes, lgtm, size/L

#38 Reconcile ClusterDuckTypes, implement a collection for Ducks.
  pkg/apis/discovery/v1alpha1/clusterducktype_defaults.go
  pkg/apis/discovery/v1alpha1/clusterducktype_defaults_test.go
  pkg/apis/discovery/v1alpha1/clusterducktype_types.go
  pkg/apis/discovery/v1alpha1/clusterducktype_types_test.go
  pkg/apis/discovery/v1alpha1/clusterducktype_validation.go
  pkg/apis/discovery/v1alpha1/clusterducktype_validation_test.go
  pkg/apis/discovery/v1alpha1/zz_generated.deepcopy.go
  pkg/collection/duck_sort.go
  pkg/collection/ducks.go
  pkg/collection/ducks_test.go
  pkg/reconciler/clusterducktype/clusterducktype.go
Labels: approved, cla: yes, lgtm, size/XXL

#39 introduce the resource mapper
  pkg/collection/ducks.go
  pkg/collection/ducks_test.go
  pkg/collection/resources.go
  pkg/collection/resources_test.go
  pkg/reconciler/clusterducktype/clusterducktype.go
  pkg/reconciler/clusterducktype/controller.go
Labels: approved, cla: yes, lgtm, size/XL

#42 upgrade the go-setup gh action to v2
  .github/workflows/go-build.yaml
  .github/workflows/go-style.yaml
  .github/workflows/go-test.yaml
  .github/workflows/go-verify.yaml
  .github/workflows/upgrade.yaml
Labels: approved, cla: yes, lgtm, size/S

#48 cucumber tests, but the state of objects is in yaml files
  pkg/reconciler/clusterducktype/clusterducktype_test.go
  pkg/reconciler/clusterducktype/features/smoke.feature
  pkg/reconciler/clusterducktype/testdata/config/smoke/initial.yaml
  pkg/reconciler/clusterducktype/testdata/config/smoke/updated.yaml
  pkg/reconciler/clusterducktype/testdata/features/bad-keys.feature
  pkg/reconciler/clusterducktype/testdata/features/smoke.feature
Labels: approved, cla: yes, lgtm, size/L
