Repository knative-sandbox/discovery, pull requests merged in 2021-03, with the labels that each got.

#155 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/discovery/v1alpha1/clusterducktype/controller.go
  pkg/client/injection/reconciler/discovery/v1alpha1/clusterducktype/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/metrics_worker.go
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/knative.dev/pkg/network/network.go
  vendor/knative.dev/pkg/reconciler/testing/clock.go
  vendor/knative.dev/pkg/system/clock.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/images/cmd.go
  vendor/knative.dev/reconciler-test/pkg/images/ko.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#156 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/environment/interfaces.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#158 fix codeowners
  .github/CODEOWNERS
Labels: approved, cla: yes, lgtm, size/S

#161 Fix #139 - Typo in README
  README.md
Labels: cla: yes, lgtm, size/XS

#159 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/informer/informed_watcher.go
  vendor/knative.dev/pkg/configmap/informer/synced_callback.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
  vendor/knative.dev/reconciler-test/pkg/state/context.go
  vendor/knative.dev/reconciler-test/pkg/state/interfaces.go
  vendor/knative.dev/reconciler-test/pkg/state/kvstore.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#143 Fix two small spelling issues
  README.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#140 Update README.md - fix addressables reference
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#165 Run all actions against main
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/XS

#164 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#167 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/client/client.go
  pkg/client/injection/client/fake/fake.go
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/microbenchmarks.sh
  vendor/knative.dev/pkg/client/injection/apiextensions/client/client.go
  vendor/knative.dev/pkg/client/injection/apiextensions/client/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/client/injection/kube/client/fake/fake.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_client.go
  vendor/knative.dev/pkg/injection/clients.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/knative.dev/reconciler-test/pkg/environment/execution.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/environment/t.go
  vendor/knative.dev/reconciler-test/pkg/feature/t.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#168 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/reconciler/testing/context.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#169 [Automated] Update actions
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#170 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/golang.org/x/xerrors/LICENSE
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/errors_go113.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/errors_xerrors.go
  vendor/github.com/google/go-cmp/cmp/report_compare.go
  vendor/github.com/google/go-cmp/cmp/report_slices.go
  vendor/github.com/google/gofuzz/.travis.yml
  vendor/github.com/google/gofuzz/CONTRIBUTING.md
  vendor/github.com/google/gofuzz/README.md
  vendor/github.com/google/gofuzz/bytesource/bytesource.go
  vendor/github.com/google/gofuzz/fuzz.go
  vendor/github.com/prometheus/common/model/time.go
  vendor/google.golang.org/grpc/balancer/grpclb/grpc_lb_v1/load_balancer_grpc.pb.go
  vendor/google.golang.org/grpc/credentials/alts/internal/proto/grpc_gcp/handshaker_grpc.pb.go
  vendor/google.golang.org/grpc/encoding/proto/proto.go
  vendor/google.golang.org/grpc/regenerate.sh
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/status/status.go
  vendor/google.golang.org/grpc/version.go
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/test/README.md
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/pkg/version/version.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/environment/namespace.go
  vendor/knative.dev/reconciler-test/pkg/environment/t.go
  vendor/knative.dev/reconciler-test/pkg/environment/timings.go
  vendor/knative.dev/reconciler-test/pkg/k8s/job.go
  vendor/knative.dev/reconciler-test/pkg/k8s/steps.go
  vendor/knative.dev/reconciler-test/pkg/k8s/wait.go
  vendor/knative.dev/reconciler-test/pkg/manifest/installer.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#145 #138 ClusterRole Validation
  config/200-clusterrole.yaml
  config/knative/addressables.duck.knative.dev.yaml
  pkg/apis/discovery/v1alpha1/clusterducktype_types.go
  pkg/apis/discovery/v1alpha1/clusterducktype_types_test.go
  pkg/apis/discovery/v1alpha1/zz_generated.deepcopy.go
  pkg/collection/ducks.go
  pkg/collection/ducks_test.go
  pkg/reconciler/clusterducktype/clusterducktype.go
  pkg/reconciler/clusterducktype/testdata/config/zoo/clusterroles.yaml
  pkg/reconciler/clusterducktype/testdata/config/zoo/updated-ears.yaml
  pkg/reconciler/clusterducktype/testdata/features/zoo.feature
Labels: approved, cla: yes, lgtm, size/XL

#172 [#171] Update test/kind/bootstrap
  test/kind/README.md
  test/kind/bootstrap.sh
Labels: approved, cla: yes, kind/bug, lgtm, size/XS

#176 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#174 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/discovery/v1alpha1/clusterducktype/controller.go
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/reconciler/testing/context.go
  vendor/knative.dev/pkg/version/version.go
  vendor/knative.dev/pkg/webhook/README.md
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/reconciler-test/pkg/environment/execution.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/k8s/job.go
  vendor/knative.dev/reconciler-test/pkg/k8s/steps.go
  vendor/knative.dev/reconciler-test/pkg/k8s/wait.go
  vendor/knative.dev/reconciler-test/pkg/manifest/installer.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L
