Repository knative-sandbox/discovery, pull requests merged in 2021-04, with the labels that each got.

#178 [#177] Update ClusterDuckType openAPI schema
  config/300-clusterducktype.yaml
Labels: approved, cla: yes, lgtm, size/M

#184 #175 clusterrole cleanup
  README.md
  pkg/reconciler/clusterducktype/clusterducktype.go
  test/e2e/clusterrole_test.go
  test/e2e/config/clusterrole/clusterrole.go
  test/e2e/config/clusterrole/clusterrole.yaml
  test/e2e/main_test.go
Labels: approved, cla: yes, lgtm, size/L

#183 [#182] Fix ClusterRole access validation plural bug
  pkg/collection/ducks.go
  pkg/collection/ducks_test.go
  pkg/reconciler/clusterducktype/testdata/config/zoo/clusterroles.yaml
  pkg/reconciler/clusterducktype/testdata/config/zoo/initial.yaml
  pkg/reconciler/clusterducktype/testdata/config/zoo/updated-furries.yaml
Labels: approved, cla: yes, lgtm, size/L

#187 Drop --strict flag on ko
  test/e2e-common.sh
Labels: approved, cla: yes, lgtm, size/XS

#180 make roleRef optional in openapi schema
  config/300-clusterducktype.yaml
  pkg/apis/discovery/v1alpha1/clusterducktype_types.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#188 Copy OWNERS_ALIASES from knative/community; fill in OWNERS files
  OWNERS
  OWNERS_ALIASES
  hack/OWNERS
Labels: approved, cla: yes, lgtm, size/L
