Repository knative-sandbox/discovery, pull requests merged in 2021-02, with the labels that each got.

#141 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#142 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#146 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#147 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/metrics/memstats.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#149 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/metrics/reflector.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#148 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#150 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#151 Add CODEOWNERS file for approvals
  .github/CODEOWNERS
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#152 update deps for 0.21
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/S
