Repository knative-sandbox/discovery, pull requests merged in 2021-07, with the labels that each got.

#204 update version of kind to default to a higher version of k8s
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/XS

#206 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/logging/warning_handler.go
  vendor/knative.dev/pkg/ptr/value.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#205 [main] Update actions
  .github/workflows/knative-go-test.yaml
Labels: approved, cla: yes, lgtm, size/XS

#208 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/discovery/v1alpha1/clusterducktype/controller.go
  vendor/github.com/gobuffalo/flect/plural_rules.go
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/buffer/buffer.go
  vendor/go.uber.org/zap/go.mod
  vendor/go.uber.org/zap/go.sum
  vendor/go.uber.org/zap/logger.go
  vendor/go.uber.org/zap/options.go
  vendor/go.uber.org/zap/sugar.go
  vendor/go.uber.org/zap/zapcore/buffered_write_syncer.go
  vendor/go.uber.org/zap/zapcore/clock.go
  vendor/go.uber.org/zap/zapcore/entry.go
  vendor/golang.org/x/net/http2/ascii.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/oauth2/google/doc.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/aws.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/basecredentials.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/clientauth.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/impersonate.go
  vendor/golang.org/x/oauth2/google/jwt.go
  vendor/golang.org/x/tools/go/ast/astutil/rewrite.go
  vendor/golang.org/x/tools/internal/gocommand/version.go
  vendor/golang.org/x/tools/internal/typeparams/doc.go
  vendor/golang.org/x/tools/internal/typeparams/notypeparams.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL
