Repository knative-sandbox/discovery, pull requests merged in 2021-09, with the labels that each got.

#218 drop unused action - replaced by knobots
  .github/workflows/upgrade.yaml
Labels: cla: yes, lgtm, size/M, approved

#217 [release-0.25] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/json/decode.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/L, approved

#219 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/reconciler/leader.go
  vendor/knative.dev/pkg/webhook/json/decode.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/L, approved

#220 [release-0.24] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/json/decode.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/L, approved

#222 [release-0.23] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/json/decode.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/L, approved

#221 [release-0.22] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/json/decode.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/L, approved

#225 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, lgtm, size/M, approved

#224 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/discovery/v1alpha1/clusterducktype/reconciler.go
  pkg/client/injection/reconciler/discovery/v1alpha1/clusterducktype/state.go
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/apis/duck/v1/podspec_defaults.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_types.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_validation.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_state.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/L, approved

#228 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, lgtm, size/S, approved

#227 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: cla: yes, lgtm, size/S, approved
